# -*- coding: utf-8 -*-
"""llm_report.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZ2bBrpO3Mgqrh07XDd-mBBVccpxSS4S
"""

import cohere
import os

co = cohere.Client(os.getenv("1wCbOP1IL8mbAyUsKQriwd7MyeClpWYc4v1DPBLe"))

def generate_llm_report(summary_text):
    prompt = f"""
أنت معلّم قرآن.

هذه بيانات تسميع الطالب:
{summary_text}

المطلوب:
- تحليل نقاط الضعف
- تقديم نصائح عملية للتثبيت
- اقتراح خطة مراجعة قصيرة

اكتب التقرير بلغة عربية واضحة وتشجيعية.
"""
    response = co.generate(
        model="command",
        prompt=prompt,
        max_tokens=300,
        temperature=0.6
    )
    return response.generations[0].text.strip()