# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDWYLn_4fjkcTrfpdRKAZCsVubl4HSgj
"""

from rapidfuzz import fuzz

def find_best_match(text_read, quran):
    best_score = 0
    best_ayah = None

    for key, ayah_text in quran.items():
        score = fuzz.ratio(text_read, ayah_text)
        if score > best_score:
            best_score = score
            best_ayah = key

    return best_ayah, best_score

def generate_summary(matches):
    """تحويل نتائج المقارنة لموجز يمكن ارساله لـ LLM"""
    summary = f"عدد المقاطع: {len(matches)}\n"
    weak = [m for m in matches if m["score"] < 85]
    summary += f"عدد النقاط الضعيفة: {len(weak)}\n"
    return summary, weak